#!/bin/bash
read -p "Please input your comment:" comment
hexo clean
hexo g
git add -A
git commit -m "$comment"
git push origin master
cp -R ~/blog/public/* ~/steinswang.github.io/
cd ~/steinswang.github.io/
git add -A
git commit -m "$comment"
git push origin master